# Generated by Django 2.2.4 on 2019-08-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.TextField()),
                ('launch_date', models.TextField()),
                ('rocket_name', models.TextField()),
                ('mission_patch_link', models.TextField()),
            ],
        ),
    ]
