# Generated by Django 2.2.4 on 2019-08-16 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='launch',
            unique_together={('flight_number', 'launch_date', 'rocket_name', 'mission_patch_link')},
        ),
    ]
