# Generated by Django 2.2.4 on 2019-08-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20190817_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='launch_date',
            field=models.DateTimeField(),
        ),
    ]
